
pub enum Button{
    LB,
    RB,
    Tab,
    CapsLock,
    Esc,
    LShift,
    RShift,
    Shift,
    LControl,
    RControl,
    Control,
    LAlt,
    RAlt,
    Alt,
    Return,
    Backspace,
    Delete,
    Char(char),
    Other(i16),

}

impl From <i16> for Button{
    fn from(value: i16) -> Self {
        match value{
            0x01 => Button::LB,
            0x02 => Button::RB,
            0x09 => Button::Tab,
            0x0d => Button::Return,
            0x08 => Button::Backspace,
            0x10 => Button::Shift,
            0x11 => Button::Control,
            0x12 => Button::Alt,
            0x14 => Button::CapsLock,
            0x1b => Button::Esc,
            0xa0 => Button::LShift,
            0xa1 => Button::RShift,
            0xa2 => Button::LControl,
            0xa3 => Button::RControl,
            0xa4 => Button::LAlt,
            0xa5 => Button::RAlt,
            0x2e => Button::Delete,
            0x30 => Button::Char('0'),
            0x31 => Button::Char('1'),
            0x32 => Button::Char('2'),
            0x33 => Button::Char('3'),
            0x34 => Button::Char('4'),
            0x35 => Button::Char('5'),
            0x36 => Button::Char('6'),
            0x37 => Button::Char('7'),
            0x38 => Button::Char('8'),
            0x39 => Button::Char('9'),
            0x41 => Button::Char('A'),
            0x42 => Button::Char('B'),
            0x43 => Button::Char('C'),
            0x44 => Button::Char('D'),
            0x45 => Button::Char('E'),
            0x46 => Button::Char('F'),
            0x47 => Button::Char('G'),
            0x48 => Button::Char('H'),
            0x49 => Button::Char('I'),
            0x4a => Button::Char('J'),
            0x4b => Button::Char('K'),
            0x4c => Button::Char('L'),
            0x4d => Button::Char('M'),
            0x4e => Button::Char('N'),
            0x4f => Button::Char('O'),
            0x50 => Button::Char('P'),
            0x51 => Button::Char('Q'),
            0x52 => Button::Char('R'),
            0x53 => Button::Char('S'),
            0x54 => Button::Char('T'),
            0x55 => Button::Char('U'),
            0x56 => Button::Char('V'),
            0x57 => Button::Char('W'),
            0x58 => Button::Char('X'),
            0x59 => Button::Char('Y'),
            0x5a => Button::Char('Z'),
            0x61 => Button::Char('a'),
            0x62 => Button::Char('b'),
            0x63 => Button::Char('c'),
            0x64 => Button::Char('d'),
            0x65 => Button::Char('e'),
            0x66 => Button::Char('f'),
            0x67 => Button::Char('g'),
            0x68 => Button::Char('h'),
            0x69 => Button::Char('i'),
            0x6a => Button::Char('j'),
            0x6b => Button::Char('k'),
            0x6c => Button::Char('l'),
            0x6d => Button::Char('m'),
            0x6e => Button::Char('n'),
            0x6f => Button::Char('o'),
            0x70 => Button::Char('p'),
            0x71 => Button::Char('q'),
            0x72 => Button::Char('r'),
            0x73 => Button::Char('s'),
            0x74 => Button::Char('t'),
            0x75 => Button::Char('u'),
            0x76 => Button::Char('v'),
            0x77 => Button::Char('w'),
            0x78 => Button::Char('x'),
            0x79 => Button::Char('y'),
            0x7a => Button::Char('z'),
            0x2c => Button::Char(','),
            0x2e => Button::Char('.'),
            0x21 => Button::Char('!'),
            0x40 => Button::Char('@'),
            0x23 => Button::Char('#'),
            0x24 => Button::Char('$'),
            0x25 => Button::Char('%'),
            0x5e => Button::Char('^'),
            0x26 => Button::Char('&'),
            0x2a => Button::Char('*'),
            0x28 => Button::Char('('),
            0x29 => Button::Char(')'),
            0x7b => Button::Char('{'),
            0x7d => Button::Char('}'),
            0x3a => Button::Char(':'),
            0x3b => Button::Char(';'),
            0x27 => Button::Char('\''),
            0x22 => Button::Char('"'),
            0x3c => Button::Char('<'),
            0x3e => Button::Char('>'),
            0x2f => Button::Char('/'),
            0x7c => Button::Char('|'),
            0x3f => Button::Char('?'),
            0x2d => Button::Char('-'),
            0x3d => Button::Char('='),
            0x2b => Button::Char('+'),
            0x60 => Button::Char('`'),
            0x7e => Button::Char('~'),
            0x5b => Button::Char('['),
            0x5d => Button::Char(']'),
            0x5f => Button::Char('_'),
            0x5c => Button::Char('\\'),
            0x20 => Button::Char(' '),
            _ => todo!()
        }
    }
}
